FROM debian:13.3

RUN su root && \
    wget https://github.com/FreePBX/sng_freepbx_debian_install/raw/master/sng_freepbx_debian_install.sh -O /tmp/sng_freepbx_debian_install.sh
RUN bash /tmp/sng_freepbx_debian_install.sh